### ISSUE TITLE
I can not find R function vol.mesh in the code named file makeShape3d.R

### ISSUE THREAD

**Issue by LHJ211** [alikhuseynov/make3dOrganoid#1]
I can not find R function vol.mesh in the code named file makeShape3d.R. who help me?

**Comment by alikhuseynov** [comment]
Hi there,
Sorry about that.
Some functions probably got deprecated or removed from original packages (they were still there when I was developing make3dOrganoid).
I think it is the case for `vol.mesh()`, this function came originally from [Arothron](https://github.com/AProfico/Arothron) package, but probably got removed by the developer. The current one should be [volendo](https://github.com/AProfico/Arothron/blob/master/R/volendo.R) or [this link](https://rdrr.io/cran/Arothron/man/volendo.html)
However, I just  included the [original function](https://github.com/alikhuseynov/make3dOrganoid/blob/master/scripts/vol.mesh_orig.R), try to add it to your R script before running `vol.mesh()` 
Hope this helps.
Let me know if there are any other issues.
Thanks

**Comment by alikhuseynov** [comment]
closing this, since there is no reply.
